spring:
  threads:
    virtual:
      enabled: true
  datasource:
    username: authservice-rw
    password: authservice-rw
    url: jdbc:postgresql://localhost:5432/authservice
jwk:
  key:
    id: custom-key-id
    private: classpath:private_key.pem
    public: classpath:public_key.pem
server:
  port: 9090
