spring:
  threads:
    virtual:
      enabled: true
  datasource:
    username: authservice-rw
    password: authservice-rw
    url: jdbc:postgresql://localhost:5432/authservice
jwk:
  persistence:
    password: password
    salt: 73616C74
server:
  port: 9090
